# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FAE Dokumentation WS19
email: Stefan.Bente@th-koeln.de
description: >- # this means to ignore newlines until "baseurl:"
  Die Dokumentation des Kurses Fachspezifischer Architektur Entwurf an der TH-KÃ¶ln im Wintersemester 2019/20.
  Die Dokementation umfasst alle Teams, sowie den Team umfassenden Teil der allgemeingeltenden Sprache (ubiquitous
  language).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ArchiLab_CIDE
github_username: Archi-Lab-FAE



# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
include:
  - '_pages'
exclude:
  - 'README.md'
  - 'Jenkinsfile'
  - 'nginx.default.conf'
  - 'Dockerfile'
  - 'pipeline.groovy'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'docker-compose.prod.yml'
  - 'docker-compose.dev.yml'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
